In [1]:
import numpy as np

In [6]:
a = np.ones((3,2))

In [7]:
np.ones_like(a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
np.diag((2,1))

array([[2, 0],
       [0, 1]])

In [54]:
np.eye(1,2)

array([[1., 0.]])

In [22]:
np.random.rand(5)

array([0.78055145, 0.63786501, 0.30659115, 0.85958406, 0.33390199])

In [24]:
np.triu(a)

array([[1., 1.],
       [0., 1.],
       [0., 0.]])

In [28]:
for x in range(5,7,2):
    print(x)

5


In [33]:
np.concatenate((a, a,a), axis = 1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
A = np.arange(9)
np.clip(A, 3,None)

array([3, 3, 3, 3, 4, 5, 6, 7, 8])

In [42]:
np.concatenate((A, [1,2,2], [2,3,3]))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 2, 2, 3, 3])

In [48]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [49]:
np.cumsum(A)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [61]:
np.eye(1,30)
#np.repeat(A, 3)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [75]:
A = np.eye(4)
print(A)
np.repeat(A,3,axis=0)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [77]:
np.pad(A, ((0,0),(1,0)), mode='constant')

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
A.shape

(4, 4)

In [82]:
U,E,V = np.linalg.svd(A, full_matrices = False)
print(V)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [98]:
np.argmax(np.array([[0,1],[10000,2]]))

2

In [103]:
np.all(A[1:1] > 0)

True

In [109]:
int(A)

TypeError: only size-1 arrays can be converted to Python scalars

In [123]:
A = np.eye(9)
print(A[(np.where(A > 0))])

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [125]:
A[np.where(np.logical_and(A > 0, A == 1))]

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
A = np.arange(10)
np.random.shuffle(A)
print(A)

[0 5 1 7 3 9 2 4 8 6]


In [140]:
np.random.uniform(0,9)

2.3136537185951154

In [173]:
y = lambda x,y: x + x
y(1,2)

2

In [177]:
str.split(",")

[',']