In [1]:
import numpy as np

In [2]:
round(2.1)

2

In [10]:
round(3.5)

4

In [8]:
np.round(4.6)

5.0

In [15]:
np.ogrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [19]:
A = np.array([1,2])
%timeit A.dot(A)

747 ns ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
int(4.5)

4

In [21]:
int(4.8)

4

In [24]:
int(5.9999999)

5

In [25]:
A = [1,2,3]
B = [1,2,3]
A ==B


True

In [26]:
A is B

False

In [27]:
C = A

In [28]:
C is A

True

In [42]:
A = np.array([1.5,2.5])


np.round(A)

array([2., 2.])

In [43]:
round(1.5)

2

In [44]:
round(2.5)

2

In [48]:
A = np.array([[1.5,2.5],[1,1]])
A[np.newaxis,:]

array([[[1.5, 2.5],
        [1. , 1. ]]])

In [53]:
A = np.array([[1,2], 
              [2,3]])
print(A)

[[1 2]
 [2 3]]


In [54]:
print(A.ravel())

[1 2 2 3]


In [63]:
print(np.ones((2)))

[1. 1.]


In [65]:
print(np.ones((1,2)))

[[1. 1.]]


In [68]:
A = np.ones((2))
B = np.ones((2,1))
print(A+B)

[[2. 2.]
 [2. 2.]]


In [71]:
A = np.array([1,2,3])
print(A.reshape(1,3))
print(A)

[[1 2 3]]
[1 2 3]
