In [4]:
l = [4,2,1,5,3]
l[1:4]

[2, 1, 5]

In [7]:
"Hallo {}".format('Duc')

'Hallo Duc'

In [33]:
"{:04.2f}".format(5/3)

'1.67'

In [38]:
if 'ell' in 'ello':
    print("3")

3


In [39]:
3 is 3

True

In [44]:
x = "3"
y = "3"
x == y

True

In [45]:
x is y

True

SyntaxError: invalid syntax (<ipython-input-42-987c988965e6>, line 1)

In [46]:
import numpy as np
A = np.array([[1,1],[1,1]])

In [48]:
sum(sum(A))

4

In [59]:
def fast1(X):
    UNEVEN = X[1::2, 1::2]
    EVEN = X[::2, ::2]
    return sum(sum(EVEN)) + sum(sum(UNEVEN))

In [60]:
A = np.array([[1,2], [4,5]])

In [61]:
fast1(A)

6

In [58]:
print(A[::2,::2])

ValueError: slice step cannot be zero

In [65]:
np.sum(np.array([[2,1], 
                 [2,1]]), axis = 1)

array([3, 3])

In [76]:
print(np.array([[1,2],
                [3,4], 
                [5,6]])[::2, ::2])

[[1]
 [5]]


In [77]:
A = np.array([
    [[1,2],
     [1,2]], 
    [[1,2],
     [1,2]], 
    [[1,2],
     [1,2]]
])

In [84]:
np.sum(A, axis = 0)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [85]:
def fast2(X, th):
    summed = np.sum(X, axis = 2)
    select = summed > th
    return np.sum(summed[select])

In [87]:
a = np.array([0.0, 10.0, 20.0, 30.0])
a[:, np.newaxis, np.newaxis]

array([[[ 0.]],

       [[10.]],

       [[20.]],

       [[30.]]])

In [106]:
A = np.array([[1,2], 
              [3,4]])
print(A[np.newaxis, :])
print(A.T[:, np.newaxis])

[[[1 2]
  [3 4]]]
[[[1 3]]

 [[2 4]]]


In [91]:
B = np.array([[10, 10], 
              [5,5]])

In [92]:
A + B

array([[11, 12],
       [ 8,  9]])

In [97]:
E = np.array([1])
def lol(X):
    X = X * 2
    return X
print(lol(E))
print(E)

B = [1]
print(lol(B))
print(B)

[2]
[1]
[1, 1]
[1]


In [100]:
round(1 / 2.0)

0